### ISSUE TITLE
Documentación de método LibreDTE::post indica valor retornado de tipo 'Entrega'

### ISSUE THREAD

**Issue by frsmoray** [LibreDTE/libredte-sdk-php#4]
La línea
https://github.com/LibreDTE/libredte-sdk-php/blob/master/sdk/LibreDTE.php#L80

apunta un valor retornado de tipo 'Entrega' ya que en esa anotación @return la primera palabra indica el tipo de valor devuelto por el método.

Deberia ser
`@return array Entrega resultado de la consulta por POST`

Saludos!

**Comment by estebandelaf** [comment]
Efectivamente las documentaciones están "no estandarizadas" y tienen problemas como el que mencionas.

Eres bienvenido a hacer un pull request con la corrección :)

**Comment by frsmoray** [comment]
Genial, este fin de semana lo elaboro 😄. Saludos!
